"""add document review and coverage tables

Revision ID: d8891057ed31
Revises:
Create Date: 2026-04-16 18:02:43.109655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8891057ed31'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('project_id', sa.String(length=64), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('doc_type', sa.String(length=64), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('content_json', sa.JSON(), nullable=True),
        sa.Column('metadata_json', sa.JSON(), nullable=True),
        sa.Column('created_by', sa.String(length=64), nullable=False),
        sa.Column('updated_by', sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)

    op.create_table('document_versions',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('document_id', sa.String(length=64), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('content_json', sa.JSON(), nullable=True),
        sa.Column('change_description', sa.Text(), nullable=True),
        sa.Column('created_by', sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_versions_version'), 'document_versions', ['version'], unique=False)

    op.create_table('review_tasks',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('document_id', sa.String(length=64), nullable=False),
        sa.Column('document_version', sa.Integer(), nullable=False),
        sa.Column('project_id', sa.String(length=64), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('review_type', sa.String(length=32), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=False),
        sa.Column('assignee_ids', sa.JSON(), nullable=True),
        sa.Column('due_date', sa.String(length=32), nullable=True),
        sa.Column('config_json', sa.JSON(), nullable=True),
        sa.Column('result_json', sa.JSON(), nullable=True),
        sa.Column('created_by', sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_tasks_document_id'), 'review_tasks', ['document_id'], unique=False)
    op.create_index(op.f('ix_review_tasks_project_id'), 'review_tasks', ['project_id'], unique=False)

    op.create_table('review_comments',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('review_task_id', sa.String(length=64), nullable=False),
        sa.Column('document_id', sa.String(length=64), nullable=False),
        sa.Column('parent_comment_id', sa.String(length=64), nullable=True),
        sa.Column('comment_type', sa.String(length=32), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('severity', sa.Integer(), nullable=False),
        sa.Column('line_number', sa.Integer(), nullable=True),
        sa.Column('section_path', sa.String(length=255), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('suggestion', sa.Text(), nullable=True),
        sa.Column('created_by', sa.String(length=64), nullable=False),
        sa.Column('resolved_by', sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_comments_document_id'), 'review_comments', ['document_id'], unique=False)
    op.create_index(op.f('ix_review_comments_parent_comment_id'), 'review_comments', ['parent_comment_id'], unique=False)
    op.create_index(op.f('ix_review_comments_review_task_id'), 'review_comments', ['review_task_id'], unique=False)

    op.create_table('review_checklists',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('review_task_id', sa.String(length=64), nullable=False),
        sa.Column('doc_type', sa.String(length=64), nullable=False),
        sa.Column('item_key', sa.String(length=128), nullable=False),
        sa.Column('item_text', sa.String(length=255), nullable=False),
        sa.Column('category', sa.String(length=64), nullable=True),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('checked_by', sa.String(length=64), nullable=True),
        sa.Column('sort_order', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_checklists_review_task_id'), 'review_checklists', ['review_task_id'], unique=False)

    op.create_table('review_scores',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('review_task_id', sa.String(length=64), nullable=False),
        sa.Column('document_id', sa.String(length=64), nullable=False),
        sa.Column('dimension', sa.String(length=64), nullable=False),
        sa.Column('score', sa.Float(), nullable=False),
        sa.Column('weight', sa.Float(), nullable=False),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('scored_by', sa.String(length=64), nullable=False),
        sa.Column('is_ai', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_scores_document_id'), 'review_scores', ['document_id'], unique=False)
    op.create_index(op.f('ix_review_scores_review_task_id'), 'review_scores', ['review_task_id'], unique=False)

    op.create_table('coverage_snapshots',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('project_id', sa.String(length=64), nullable=False),
        sa.Column('execution_id', sa.String(length=64), nullable=True),
        sa.Column('commit_sha', sa.String(length=64), nullable=True),
        sa.Column('branch', sa.String(length=128), nullable=True),
        sa.Column('tool_name', sa.String(length=64), nullable=False),
        sa.Column('report_format', sa.String(length=32), nullable=False),
        sa.Column('summary_json', sa.JSON(), nullable=False),
        sa.Column('created_by', sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coverage_snapshots_execution_id'), 'coverage_snapshots', ['execution_id'], unique=False)
    op.create_index(op.f('ix_coverage_snapshots_project_id'), 'coverage_snapshots', ['project_id'], unique=False)

    op.create_table('coverage_metrics',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('snapshot_id', sa.String(length=64), nullable=False),
        sa.Column('metric_type', sa.String(length=32), nullable=False),
        sa.Column('package_name', sa.String(length=255), nullable=True),
        sa.Column('file_path', sa.String(length=512), nullable=True),
        sa.Column('covered', sa.Integer(), nullable=False),
        sa.Column('total', sa.Integer(), nullable=False),
        sa.Column('missed', sa.Integer(), nullable=False),
        sa.Column('percentage', sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coverage_metrics_snapshot_id'), 'coverage_metrics', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coverage_metrics_snapshot_id'), table_name='coverage_metrics')
    op.drop_table('coverage_metrics')
    op.drop_index(op.f('ix_coverage_snapshots_project_id'), table_name='coverage_snapshots')
    op.drop_index(op.f('ix_coverage_snapshots_execution_id'), table_name='coverage_snapshots')
    op.drop_table('coverage_snapshots')
    op.drop_index(op.f('ix_review_scores_review_task_id'), table_name='review_scores')
    op.drop_index(op.f('ix_review_scores_document_id'), table_name='review_scores')
    op.drop_table('review_scores')
    op.drop_index(op.f('ix_review_checklists_review_task_id'), table_name='review_checklists')
    op.drop_table('review_checklists')
    op.drop_index(op.f('ix_review_comments_review_task_id'), table_name='review_comments')
    op.drop_index(op.f('ix_review_comments_parent_comment_id'), table_name='review_comments')
    op.drop_index(op.f('ix_review_comments_document_id'), table_name='review_comments')
    op.drop_table('review_comments')
    op.drop_index(op.f('ix_review_tasks_project_id'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_document_id'), table_name='review_tasks')
    op.drop_table('review_tasks')
    op.drop_index(op.f('ix_document_versions_version'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
